//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/8. VRRubeGoldberg/VRInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @VRInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @VRInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""VRInputActions"",
    ""maps"": [
        {
            ""name"": ""Default"",
            ""id"": ""c37a1ae8-1a40-4897-9239-2be7b31d358e"",
            ""actions"": [
                {
                    ""name"": ""Primary Button Right Hand"",
                    ""type"": ""Value"",
                    ""id"": ""5f80cf5e-2c77-45c0-8d26-947751e9b3e3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""X Button Left Hand"",
                    ""type"": ""Value"",
                    ""id"": ""8b08527e-0868-4c91-a40b-cb5b0193d810"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f2c2159d-2f81-4217-bf18-e17a30f1af68"",
                    ""path"": ""<OculusTouchController>/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Primary Button Right Hand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8527ffa7-58e8-4fad-9852-d84d12e552f6"",
                    ""path"": ""<XRInputV1::Oculus::OculusTouchControllerOpenXR>{LeftHand}/primarybutton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""X Button Left Hand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Default
        m_Default = asset.FindActionMap("Default", throwIfNotFound: true);
        m_Default_PrimaryButtonRightHand = m_Default.FindAction("Primary Button Right Hand", throwIfNotFound: true);
        m_Default_XButtonLeftHand = m_Default.FindAction("X Button Left Hand", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Default
    private readonly InputActionMap m_Default;
    private IDefaultActions m_DefaultActionsCallbackInterface;
    private readonly InputAction m_Default_PrimaryButtonRightHand;
    private readonly InputAction m_Default_XButtonLeftHand;
    public struct DefaultActions
    {
        private @VRInputActions m_Wrapper;
        public DefaultActions(@VRInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @PrimaryButtonRightHand => m_Wrapper.m_Default_PrimaryButtonRightHand;
        public InputAction @XButtonLeftHand => m_Wrapper.m_Default_XButtonLeftHand;
        public InputActionMap Get() { return m_Wrapper.m_Default; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultActions set) { return set.Get(); }
        public void SetCallbacks(IDefaultActions instance)
        {
            if (m_Wrapper.m_DefaultActionsCallbackInterface != null)
            {
                @PrimaryButtonRightHand.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnPrimaryButtonRightHand;
                @PrimaryButtonRightHand.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnPrimaryButtonRightHand;
                @PrimaryButtonRightHand.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnPrimaryButtonRightHand;
                @XButtonLeftHand.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnXButtonLeftHand;
                @XButtonLeftHand.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnXButtonLeftHand;
                @XButtonLeftHand.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnXButtonLeftHand;
            }
            m_Wrapper.m_DefaultActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PrimaryButtonRightHand.started += instance.OnPrimaryButtonRightHand;
                @PrimaryButtonRightHand.performed += instance.OnPrimaryButtonRightHand;
                @PrimaryButtonRightHand.canceled += instance.OnPrimaryButtonRightHand;
                @XButtonLeftHand.started += instance.OnXButtonLeftHand;
                @XButtonLeftHand.performed += instance.OnXButtonLeftHand;
                @XButtonLeftHand.canceled += instance.OnXButtonLeftHand;
            }
        }
    }
    public DefaultActions @Default => new DefaultActions(this);
    public interface IDefaultActions
    {
        void OnPrimaryButtonRightHand(InputAction.CallbackContext context);
        void OnXButtonLeftHand(InputAction.CallbackContext context);
    }
}
